gr0108/gr0108/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/", include("polls.urls")),
    path("routing/", include("routing_lesson.urls")),
    path("polls_generic/", include("polls_generic.urls")),
    path("auth/", include("users.urls")),
]

gr0108/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("api/questions/", views.question_collection, name="api_question_collection"),
]

gr0108/polls_generic/urls.py
from django.urls import path
from . import views

app_name = "polls_generic"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:question_id>/", views.DetailView.as_view(), name="detail"),
    path("<int:question_id>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

gr0108/routing_lesson/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path("", views.index),
    path("articles/2003/", views.special_case_2003),
    re_path("articles/(?P<year>[0-9]{4})/$", views.year_archive),
    re_path("articles/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$", views.month_archive),
    path("articles/<int:year>/<int:month>/<slug:slug>/", views.article_detail),
]

gr0108/users/urls.py
from django.urls import path, include
from . import views


app_name = "users"
urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
]

gr0108/polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def  __str__(self):
        return f" id: {self.id} - {self.question_text}"

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def  __str__(self):
        return self.choice_text

gr0108/polls_generic/models.py
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def  __str__(self):
        return f" id: {self.id} - {self.question_text}"

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def  __str__(self):
        return self.choice_text

gr0108/routing_lesson/models.py
from django.db import models

# Create your models here.

gr0108/users/models.py
from django.db import models

# Create your models here.

gr0108/users/forms.py
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email", )

gr0108/polls/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from rest_framework.decorators import api_view
from  rest_framework.response import Response
from .serializers import QuestionSerializer

from .models import Question, Choice



@api_view(["GET"])
def question_collection(request):
    if request.method == "GET":
        questions = Question.objects.all()
        serializer = QuestionSerializer(questions, many=True)
        return Response(serializer.data)


def index(request: HttpRequest) -> HttpResponse:
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {
        "latest_question_list": latest_question_list
    }
    return render(request, "polls/index.html", context)

def detail(request: HttpRequest, question_id) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})

def results(request: HttpRequest, question_id) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request: HttpRequest, question_id) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

gr0108/polls_generic/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = "polls_generic/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls_generic/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls_generic/results.html"






def vote(request: HttpRequest, question_id) -> HttpResponse:
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls_generic/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


gr0108/routing_lesson/views.py
from django.http import HttpRequest, HttpResponse

def index(request: HttpRequest) -> HttpResponse:
    return HttpResponse("Rout 1 is here")

def special_case_2003(request: HttpRequest) -> HttpResponse:
    return HttpResponse("спеціальний випадок 2003")

def year_archive(request: HttpRequest, year: int | None) -> HttpResponse:
    return HttpResponse(f"архів за рік {year}")

def month_archive(request: HttpRequest, year: int | None, month: int | None) -> HttpResponse:
    return HttpResponse(f"архів за місяць {month} - {year}")

def article_detail(
        request: HttpRequest,
        year: int | None,
        month: int | None,
        slug: str | None,
) -> HttpResponse:
    return HttpResponse(f"деталізація статті {slug} за {month} - {year}")



# Create your views here.

gr0108/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.urls import reverse
from .forms import CustomUserCreationForm

def dashboard(request):
    return render(request, "dashboard.html")

def register(request):
    if request.method == "GET":
        return render(
            request, "users/templates/register.html",
            {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse("dashboard"))

gr0108/polls/templates/polls/base.html
<!doctype html>
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    {% block heading %}
        <h1>my first app: POLLS</h1>
    {% endblock heading %}

    {% block content %}
    {% endblock content %}
    {% block final %}
    <hr>
    <p>
        Copyright 2022-{% now "Y"%}
    </p>
    <hr>
    {% endblock final %}
</body>
</html>

gr0108/polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block heading %}
    {{block.super}}
    <h2>question:</h2>
<hr>
{% endblock heading %}

{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h3>{{ question.question_text }}</h3></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{ choice.id }}">
            <label for="choice{{forloop.counter}}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>
{% endblock content %}

gr0108/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block heading %}
    {{block.super}}
    <h2>questions:</h2>
<hr>
{% endblock heading %}

{% block content %}

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock content %}


<!-- forloop.counter
forloop.counter0
forloop.revcounter
forloop.revcounter0
forloop.first
forloop.last
forloop.parentloop -->




gr0108/polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block heading %}
    {{block.super}}
    <h2>{{question.question_text}}:</h2>
<hr>
{% endblock heading %}

{% block content %}
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} --> {{ choice.votes }} vote {{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again!</a>
{% endblock content %}

gr0108/polls_generic/templates/polls_generic/base.html
<html>
<body>
    {% block heading %}
        <h1>my first app: POLLS</h1>
    {% endblock heading %}

    {% block content %}
    {% endblock content %}
    {% block final %}
    <hr>
    <p>
        Copyright 2022-{% now "Y"%}
    </p>
    <hr>
    {% endblock final %}
</body>
</html>

gr0108/polls_generic/templates/polls_generic/detail.html
{% extends "polls/base.html" %}

{% block heading %}
    {{block.super}}
    <h2>question:</h2>
<hr>
{% endblock heading %}

{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h3>{{ question.question_text }}</h3></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{ choice.id }}">
            <label for="choice{{forloop.counter}}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>
{% endblock content %}

gr0108/polls_generic/templates/polls_generic/index.html
{% extends "polls/base.html" %}

{% block heading %}
    {{block.super}}
    <h2>questions:</h2>
<hr>
{% endblock heading %}

{% block content %}

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls_generic:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock content %}


<!-- forloop.counter
forloop.counter0
forloop.revcounter
forloop.revcounter0
forloop.first
forloop.last
forloop.parentloop -->




gr0108/polls_generic/templates/polls_generic/results.html
{% extends "polls/base.html" %}

{% block heading %}
    {{block.super}}
    <h2>{{question.question_text}}:</h2>
<hr>
{% endblock heading %}

{% block content %}
<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} --> {{ choice.votes }} vote {{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls_generic:detail' question.id %}">Vote again!</a>
{% endblock content %}

gr0108/users/templates/base.html
<!--users/templates/base.html-->

<style>
    label, input {
        display: block;
    }
    span.helptext {
        display: none;
    }
</style>

<h3>Users auth</h3>

{% block content %}
{% endblock %}

gr0108/users/templates/dashboard.html
<!--users/templates/dashboard.html-->

{% extends "base.html" %}

{% block content %}
Hello, {{ user.username|default:"Guest"}}!

<div>
    {% if user.is_authenticated %}
        <p><a href="{% url 'users:logout' %}">Logout</a></p>

        <p><a href="{% url 'users:password_change' %}">Change password</a></p>
    {% else %}
        <a href="{% url 'users:login' %}">Login</a>
    {% endif %}

</div>
{% endblock %}

gr0108/users/templates/register.html
{% extends 'base.html' %}

{% block content %}

<h4>Register</h4>

<form method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Register">
</form>

<a href="{% url 'login' %}">Back to login</a>

{% endblock %}